### PR TITLE
add Auriga's Extra

### PR DESCRIPTION
**Pull request by Auriga05**
Please mod, thank you. (tl: pls mod thx)

### CODE REVIEW

**Comment by kyairie** [comment]
00:08:528 (1,2,3,4,5,6,7,8,9) - commit to the square aes here or abandon it, looks wack

00:38:365 (10,1,2) - angle sorta fucky wide but if ur into that idc

00:42:419 (4) - could follow the drum/percussion bits here

00:48:905 (1,2) - mute sliderends + apply to similar

00:54:094 (5) - nc

00:59:283 (1,2,3,4,5,6,7) - could go a bit more spaced

01:15:175 (2,4) - stack broke
01:17:445 (1,1) -  ^

01:42:094 (6) - nc

01:46:959 (5,1) - probs make this 1/1 slider, to better show vocal focus

02:10:634 (1,2,3,1,2,3,1,2,3,1,2,3) - think this gets too gungaspaced towards the end, consider reducing the spacing increase rate

rest seems rankable? like its not the best but idk what to say im braindead and didnt do a thorough mod, might look again later

@Mrgglock should take a crack at modding this too

**Comment by Mrgglock** [comment]
00:17:932 (2,3,4,5) - consider higher spacing for more intense double tempo

00:19:392 (1) - consider higher spacing for downbeat as it is currently quite similar to 00:17:122 (3,4,5) - 

01:11:770 (7) - kick slider?

02:14:526 (1) - stack broke 

02:35:931 (1,2,3,4) - this has the same piano pitch and is more unique and intense than 02:35:282 (1,2,3,4) - and i think deserves a different flow

02:37:715 (1) - this part is just a bridge but has way too big spacing, like way bigger than anything i've seen in the map, i suggest making kiai spacing bigger cuz bridge shouldnt be this much more hard

03:17:120 (1) - suggest making 1/3s bigger in spacing to differentiate from 1/4s, it has more window for error anyway

03:21:985 (1,1) - stack

03:35:931 (7,1) - too far



04:08:525 (1) - ambiguous but ok

**Comment by Auriga05** [comment]
kyai
00:08:528 is accidental but i'm making it more square
00:38:365 no change
00:42:419 that part would be denser including 5, 6 which i don't like
00:48:905 i'm on lazer 
00:59:283 moved 6 slightly, should this also apply to 02:13:228 (1,2,3,4,5,6,7,8) - ?, i also slightly moved some circles
fixed stacks and nc
01:46:959 doesn't feel like it changes anything
02:10:634 (1,2,3,1,2,3,1,2,3,1,2,3) - decreased spacing

mrgg
00:17:932 i don't know what you mean, but i increased spacing
00:18:905 (1,2,1,2,3,4,5) - ok i moved these left
01:11:770 - okk
02:14:526 - cap
02:35:931 - made spacing more distinct but retained pattern because i think it should have the same idea
02:37:715 - ok will increase all kiai spacing slightly, also slightly nerf this section
03:17:120 - added new combos to differentiate, this part doesn't have 1/4s nearby anyway so i didn't feel the need to differentiate
03:21:985 - ok
03:35:931 - moved 7 closer
04:08:525 - what should i even do

03:43:066 (1,2,3,4,5,6,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,1) - also changed position so that first circle is stacked

**Comment by Mrgglock** [comment]
@kyairie Please follow up, and merge if appropriate. Thank you

**Comment by kyairie** [comment]
02:21:823 (1,1) - Not sure about having this jump be spaced across the screen. In my opinion, the spacing makes the circles seem less connected as a pattern. I suggest moving 02:21:823 (1) down, somewhere around (x:30 y:130) should be better.

02:36:580 (1,1) - Spacing is too big for the low intensity break in the music, which doesn't contrast well against the jump at 02:37:553 (3,1). I suggest starting the pattern with 02:37:390 (2), or otherwise moving the triangle pattern closer to 02:36:580 (1).

03:02:202 (1) - This would look more aesthetically pleasing if you used a slidershape more like 02:49:391 (1). In my opinion, it is more visually striking than the flatter wave you have right now.

After applying these, I'd be good with merging. 👍

**Comment by kyairie** [comment]
yea lgtm except i didnt look if its good to me

👍

**Pull request merged**
